"""
Exploration script: reverse-engineer the exact lap time formula.

Loads precomputed compact data from solution/races_compact.json
(generated by preprocess.py).

Formula hypothesis:
  lap_time = base + co[tire] + max(0, age - cliff[tire]) * deg[tire] * (tb + tc * temp)

  age starts at 0, incremented to 1 before first lap calc.
  Pit at end of lap: adds pit_lane_time, resets age to 0.

For a stint of length L on tire with cliff C (where L > C):
  degradation contribution = deg[tire] * temp_f * sum_{a=C+1}^{L} (a - C)
                           = deg[tire] * temp_f * k*(k+1)/2   where k = L - C

  offset contribution = co[tire] * L
  base contribution = base * total_laps  (same for all drivers, cancels out in ranking)
  pit contribution = pit_time * num_pits
"""

import json
import os
import sys
import time

COMPACT_PATH = os.path.join(os.path.dirname(__file__), "races_compact.json")


def load_compact():
    with open(COMPACT_PATH) as f:
        return json.load(f)


def predict(pc, co, deg, cliff, tb, tc):
    """Predict finishing order for a compact race record."""
    temp_f = tb + tc * pc["t"]
    times = []
    for did, stints, num_pits in pc["d"]:
        t = pc["b"] * pc["n"] + pc["p"] * num_pits
        for tire_i, slen in stints:
            t += co[tire_i] * slen
            c = cliff[tire_i]
            if slen > c:
                k = slen - c
                t += k * (k + 1) / 2.0 * deg[tire_i] * temp_f
        times.append((did, t))
    times.sort(key=lambda x: x[1])
    return [d for d, _ in times]


def accuracy(pcs, co, deg, cliff, tb, tc):
    ok = 0
    for pc in pcs:
        if predict(pc, co, deg, cliff, tb, tc) == pc["e"]:
            ok += 1
    return ok / len(pcs)


def main():
    t0 = time.time()

    print("Loading compact data...")
    all_races = load_compact()
    print(f"Loaded {len(all_races)} races in {time.time()-t0:.1f}s")

    sample = all_races[:200]
    full = all_races[:1000]

    temps = sorted(set(r["t"] for r in all_races))
    print(f"Unique temps: {temps[:5]}...{temps[-5:]}")
    print(f"Using {len(sample)} for sweeps, {len(full)} for validation.\n")

    # ─── PHASE 1: Compound offsets (no degradation) ──────────────────────
    print("=== PHASE 1: Compound offsets ===")
    best1 = 0
    best_co = [0, 0, 0]
    no_deg = [0, 0, 0]
    no_cliff = [999, 999, 999]

    for si in range(-20, 1):
        s = si * 0.1
        for hi in range(0, 25):
            h = hi * 0.1
            co = [s, 0.0, h]
            a = accuracy(sample, co, no_deg, no_cliff, 1.0, 0.0)
            if a > best1:
                best1 = a
                best_co = co[:]
                print(f"  S={s:+.1f} H={h:+.1f} => {a:.4f}")

    # Refine at 0.01
    sc, hc = best_co[0], best_co[2]
    for si in range(-10, 11):
        for hi in range(-10, 11):
            co = [round(sc + si * 0.01, 3), 0.0, round(hc + hi * 0.01, 3)]
            a = accuracy(sample, co, no_deg, no_cliff, 1.0, 0.0)
            if a > best1:
                best1 = a
                best_co = co[:]
                print(f"  S={co[0]:+.3f} H={co[2]:+.3f} => {a:.4f}")

    print(f"Phase 1: {best1:.4f}  co={best_co}\n")

    # ─── PHASE 2: Degradation (cliff=0, temp_factor=1) ──────────────────
    print("=== PHASE 2: Degradation (cliff=0, tf=1) ===")
    best2 = 0
    best_deg = [0, 0, 0]

    # Coarse step 0.02
    for dsi in range(0, 16):
        ds = dsi * 0.02
        for dmi in range(0, 11):
            dm = dmi * 0.02
            for dhi in range(0, 8):
                dh = dhi * 0.02
                deg = [ds, dm, dh]
                a = accuracy(sample, best_co, deg, [0, 0, 0], 1.0, 0.0)
                if a > best2:
                    best2 = a
                    best_deg = deg[:]
                    print(f"  S={ds:.2f} M={dm:.2f} H={dh:.2f} => {a:.4f}")

    # Refine at 0.005
    sc, mc, hc = best_deg
    for dsi in range(-8, 9):
        for dmi in range(-8, 9):
            for dhi in range(-8, 9):
                deg = [max(0, round(sc + dsi * 0.005, 4)),
                       max(0, round(mc + dmi * 0.005, 4)),
                       max(0, round(hc + dhi * 0.005, 4))]
                a = accuracy(sample, best_co, deg, [0, 0, 0], 1.0, 0.0)
                if a > best2:
                    best2 = a
                    best_deg = deg[:]
                    print(f"  S={deg[0]:.4f} M={deg[1]:.4f} H={deg[2]:.4f} => {a:.4f}")

    print(f"Phase 2: {best2:.4f}  deg={best_deg}\n")

    # ─── PHASE 2b: Cliffs ───────────────────────────────────────────────
    print("=== PHASE 2b: Cliffs ===")
    best2b = best2
    best_cliff = [0, 0, 0]

    for cs in range(0, 10):
        for cm in range(0, 10):
            for ch in range(0, 12):
                a = accuracy(sample, best_co, best_deg, [cs, cm, ch], 1.0, 0.0)
                if a > best2b:
                    best2b = a
                    best_cliff = [cs, cm, ch]
                    print(f"  cs={cs} cm={cm} ch={ch} => {a:.4f}")

    print(f"Phase 2b: {best2b:.4f}  cliff={best_cliff}\n")

    # ─── PHASE 3: Temperature ───────────────────────────────────────────
    print("=== PHASE 3: Temperature ===")
    best3 = best2b
    best_tb, best_tc = 1.0, 0.0

    for tbi in range(-50, 150):
        tb = tbi * 0.01
        for tci in range(-30, 80):
            tc = tci * 0.001
            a = accuracy(sample, best_co, best_deg, best_cliff, tb, tc)
            if a > best3:
                best3 = a
                best_tb, best_tc = tb, tc
                print(f"  tb={tb:.2f} tc={tc:.3f} => {a:.4f}")

    # Refine
    tbc, tcc = best_tb, best_tc
    for dtb in range(-20, 21):
        tb = round(tbc + dtb * 0.001, 4)
        for dtc in range(-20, 21):
            tc = round(tcc + dtc * 0.0001, 5)
            a = accuracy(sample, best_co, best_deg, best_cliff, tb, tc)
            if a > best3:
                best3 = a
                best_tb, best_tc = tb, tc
                print(f"  tb={tb:.4f} tc={tc:.5f} => {a:.4f}")

    print(f"Phase 3: {best3:.4f}  tb={best_tb} tc={best_tc}\n")

    # ─── PHASE 4: Validate on 1000 + fine-tune ─────────────────────────
    print("=== PHASE 4: Full validation (1000 races) ===")
    full_acc = accuracy(full, best_co, best_deg, best_cliff, best_tb, best_tc)
    print(f"Initial: {full_acc:.4f}")

    for round_n in range(3):
        improved = False

        # Offsets
        sc, hc = best_co[0], best_co[2]
        for dsi in range(-10, 11):
            for dhi in range(-10, 11):
                co = [round(sc + dsi * 0.01, 4), 0.0, round(hc + dhi * 0.01, 4)]
                a = accuracy(full, co, best_deg, best_cliff, best_tb, best_tc)
                if a > full_acc:
                    full_acc = a
                    best_co = co[:]
                    improved = True
                    print(f"  (off) S={co[0]} H={co[2]} => {a:.4f}")

        # Deg
        dc = best_deg[:]
        for dsi in range(-5, 6):
            for dmi in range(-5, 6):
                for dhi in range(-5, 6):
                    deg = [max(0, round(dc[0] + dsi * 0.001, 5)),
                           max(0, round(dc[1] + dmi * 0.001, 5)),
                           max(0, round(dc[2] + dhi * 0.001, 5))]
                    a = accuracy(full, best_co, deg, best_cliff, best_tb, best_tc)
                    if a > full_acc:
                        full_acc = a
                        best_deg = deg[:]
                        improved = True
                        print(f"  (deg) {deg} => {a:.4f}")

        # Temp
        for dtb in range(-10, 11):
            tb = round(best_tb + dtb * 0.002, 5)
            for dtc in range(-10, 11):
                tc = round(best_tc + dtc * 0.0002, 6)
                a = accuracy(full, best_co, best_deg, best_cliff, tb, tc)
                if a > full_acc:
                    full_acc = a
                    best_tb, best_tc = tb, tc
                    improved = True
                    print(f"  (temp) tb={tb} tc={tc} => {a:.4f}")

        # Cliffs
        cc = best_cliff[:]
        for cs in range(max(0, cc[0] - 2), cc[0] + 3):
            for cm in range(max(0, cc[1] - 2), cc[1] + 3):
                for ch in range(max(0, cc[2] - 2), cc[2] + 3):
                    a = accuracy(full, best_co, best_deg, [cs, cm, ch], best_tb, best_tc)
                    if a > full_acc:
                        full_acc = a
                        best_cliff = [cs, cm, ch]
                        improved = True
                        print(f"  (cliff) {best_cliff} => {a:.4f}")

        if not improved:
            print(f"  Round {round_n+1}: no improvement, stopping.")
            break
        print(f"  Round {round_n+1}: improved to {full_acc:.4f}")

    # ─── FINAL RESULTS ──────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("FINAL RESULTS")
    print("=" * 60)
    print(f"Accuracy (1000 races): {full_acc:.4f}")
    print(f"compound_offset: SOFT={best_co[0]}, MEDIUM=0.0, HARD={best_co[2]}")
    print(f"deg_rate:        SOFT={best_deg[0]}, MEDIUM={best_deg[1]}, HARD={best_deg[2]}")
    print(f"cliff:           SOFT={best_cliff[0]}, MEDIUM={best_cliff[1]}, HARD={best_cliff[2]}")
    print(f"temp_base:       {best_tb}")
    print(f"temp_coeff:      {best_tc}")
    print(f"\nFormula:")
    print(f"  lap_time = base + co[tire] + max(0, age - cliff[tire]) * deg[tire] * (tb + tc*temp)")
    print(f"  age: 0->1 before first lap; reset to 0 on pit stop")

    # Cross-validate on 30k
    print("\n--- Cross-validation (all 30k) ---")
    all_acc = accuracy(all_races, best_co, best_deg, best_cliff, best_tb, best_tc)
    print(f"All 30000 races: {all_acc:.4f}")

    # Test cases
    test_in = os.path.join(os.path.dirname(__file__), "..", "data", "test_cases", "inputs")
    test_out = os.path.join(os.path.dirname(__file__), "..", "data", "test_cases", "expected_outputs")
    if os.path.exists(test_in) and os.path.exists(test_out):
        print("\n--- Test cases ---")
        ok = total = 0
        for fn in sorted(os.listdir(test_in)):
            if not fn.endswith(".json"):
                continue
            with open(os.path.join(test_in, fn)) as f:
                tc_data = json.load(f)
            exp_path = os.path.join(test_out, fn)
            if not os.path.exists(exp_path):
                continue
            with open(exp_path) as f:
                exp = json.load(f)
            # Precompute from raw format
            cfg = tc_data["race_config"]
            drivers = []
            for strat in tc_data["strategies"].values():
                tire_idx = {"SOFT": 0, "MEDIUM": 1, "HARD": 2}
                tire = strat["starting_tire"]
                pit_map = {ps["lap"]: ps["to_tire"] for ps in strat["pit_stops"]}
                stints = []
                st = tire_idx[tire]
                sl = 0
                for lap in range(1, cfg["total_laps"] + 1):
                    sl += 1
                    if lap in pit_map:
                        stints.append([st, sl])
                        st = tire_idx[pit_map[lap]]
                        sl = 0
                stints.append([st, sl])
                drivers.append([strat["driver_id"], stints, len(strat["pit_stops"])])
            pc = {"b": cfg["base_lap_time"], "p": cfg["pit_lane_time"],
                  "t": cfg["track_temp"], "n": cfg["total_laps"],
                  "d": drivers, "e": exp["finishing_positions"]}
            pred = predict(pc, best_co, best_deg, best_cliff, best_tb, best_tc)
            total += 1
            if pred == exp["finishing_positions"]:
                ok += 1
            else:
                print(f"  MISS {fn}: pred={pred[:3]} exp={exp['finishing_positions'][:3]}")
        print(f"Test accuracy: {ok}/{total}")

    print(f"\nTotal time: {time.time() - t0:.1f}s")


if __name__ == "__main__":
    main()
